### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by samihoda** [coldbox-modules/disable-bot-sessions#3]
The fileRead in /modules/disable-bot-sessions/interceptors/DisableBotSessions.cfc fails. It returns /config/bots.json, which doesn't exist, instead of /modules/disable-bot-sessions/config/bots.json. I believe expandPath tends to return the framework root, instead of the current path inside the modules folder.

**Comment by samihoda** [comment]
I should add this is on Lucee latest, with ColdBox latest

**Comment by samihoda** [comment]
This is what my configure() function looks like:

```
function configure() {
       var currentPath = GetDirectoryFromPath( GetCurrentTemplatePath() );
        var parentDirectory = reReplace( currentPath, "[^/]+/$", "", "one" );
        var filePath = parentDirectory & "config/bots.json";    
        variables.bots = deserializeJSON( fileRead( filePath ) );   
    }
```

**Comment by elpete** [comment]
Strange.  I think the fix for this would be to read the file in during the `ModuleConfig#configure`.

**Comment by samihoda** [comment]
Not sure what that means. I'm just saying that I used commandbox to install the package, ran reinit, and it showed that the package could not find the JSON file. When I looked at the code, it seemed to be looking at the root path by using expandpath. So I suggested the change to find it by navigating through the parent directory.

**Comment by elpete** [comment]
`disable-bot-sessions@2.0.0` has been published that should fix your problem.
